# Estágio 1: Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

# Estágio 2: Produção (Nginx)
FROM nginx:stable-alpine

# 1. Copia os arquivos estáticos do build
COPY --from=builder /app/dist /usr/share/nginx/html

# 2. ATENÇÃO: Descomente esta linha para aplicar o seu try_files
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]