server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy opcional para o backend se necessário
    # location /api {
    #     proxy_pass http://lulu-backend-prod:3000;
    # }
}